### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by csulit** [caobo171/node-zklib#1]
Hoping to see more features like 

connect(callback) -> To Connect in machine.
disconnect() -> Disconnect connection with machine.
**serialNumber(callback) -> Get serial number machine.**
**version(callback) -> Get version of machine.**
enableDevice(callback) -> Enable the device.
disableDevice(callback) -> Disable the device.
getAttendance(callback) -> Get attendance data.
**clearAttendanceLog(callback) -> Clear the attendance logs from device.**
**getTime(callback) -> Get time of machine.**
**setTime(value, callback) -> Set time in machine.**
getUser(callback) -> Get all user in machine.

**Comment by caobo171** [comment]
Yeah really thanks your feedbacks , I will do it soon !! about clearAttendanceLog() , I need testing device but I'm testing on my company  machine so it's really dangerous when implementing this features so ... :))

**Comment by csulit** [comment]
Thanks, we have lot's of devices here in out office if you have to test some features you can message me :)

**Comment by emahuni** [comment]
Thank you sooooo much for this working implementation.

Also there are  bunch of undocumented methods: 

setUser
enrollUser
delUser

These are very useful, but undocumented functions, they are in zkuser.js in the other js_zklib repo.

**Comment by caobo171** [comment]
@emahuni sorry because I can't implement delete and add action in my company devices , but you guys can create it your own using executeCmd  function in zklibtcp.js and zklibudp.js , and we can read protocol command in [https://github.com/adrobinoga/zk-protocol
](url)  . 

You guys can also see how I write  enableDevice, disableDevice, freeData in these file 


Oops , in features requests, I 've already have enableDevice() and disableDevice() :)))

**Comment by csulit** [comment]
> @emahuni sorry because I can't implement delete and add action in my company devices , but you guys can create it your own using executeCmd function in zklibtcp.js and zklibudp.js , and we can read protocol command in [https://github.com/adrobinoga/zk-protocol ](url) .
> 
> You guys can also see how I write enableDevice, disableDevice, freeData in these file
> 
> Oops , in features requests, I 've already have enableDevice() and disableDevice() :)))

Do you have a tutorial on how to create executeCmd commands?

**Comment by csulit** [comment]
@caobo171  Can you show a sample of code on how to reboot specific devices via IP? :)

**Comment by caobo171** [comment]
Sorry for late response !! 
I've tried clearAttLog like this : 

  async clearAttLog () {
    return await this.executeCmd(COMMANDS.CMD_CLEAR_ATTLOG, '');
  }

**Comment by caobo171** [comment]
the function executeCmd is already available in ZklibTCP and ZkLibUDP :)) , you just need to know the CMD and put it into the params 👍

**Comment by ABRAR-E-GOHAR** [comment]
Where to import COMMANDS.CMD_CLEAR_ATTLOG
