### ISSUE TITLE
How to realtime events ,Get device real-time events

### ISSUE THREAD

**Issue by Michel0305** [caobo171/node-zklib#18]
Hello big coffee, I would like to ask, how do I register for real-time events? I executed it with a command (zkInstance.executeCmd (500, ‘’)) and nothing happened. I want to get real-time feedback from the device, such as user ’s card swipe, user authentication, etc. . . . Very need user swipe card or fingerprint operation event

**Comment by caobo171** [comment]
I've already implement realTime event, please check the readme . And how to implement it you can see in my source code, thanks !!

**Comment by Michel0305** [comment]
tks



At 2020-03-13 17:18:37, "caobo171" <notifications@github.com> wrote:

I've already implement realTime event, please check the readme . And how to implement it you can see in my source code, thanks !!
