### ISSUE TITLE
Log in check

### ISSUE THREAD

**Issue by csulit** [caobo171/node-zklib#2]
How to get the data if the client check-in or check-out the premise in getAttences?

**Comment by caobo171** [comment]
At this time there is no way to check the client is check-in or check-out , I think you can declare it in you application , which machine used for checkout or check-in and add another field to your data !

**Comment by csulit** [comment]
Yea, even in the SDK, I can't find that feature, but thank you, by the way.

**Comment by emahuni** [comment]
I thought I saw this working as in the example:

```js
  await zkInstance.getRealTimeLogs((data) => {
       // do something when some checkin
       console.log(data);
   });
```

just don't disconnect and each time there is a swipe that cb is run with data given.

**Comment by mawaridbackend** [comment]
zkInstance.getRealTimeLogs((data) => {
       // do something when some checkin
       console.log(data);
   }); this code is not working?
