### ISSUE TITLE
Type of data needed

### ISSUE THREAD

**Issue by csulit** [caobo171/node-zklib#20]
can this be a string of bio id?   or data needs to be converted??

 async executeCmd(command, data=''){
        return await this.functionWrapper(
            ()=> this.zklibTcp.executeCmd(command, data),
            ()=> this.zklibUdp.executeCmd(command , data)
        )
    }

    // unlock the door  
    executeCmd(CMD.CMD_DELETE_USERTEMP, object?)

**Comment by caobo171** [comment]
yes, it 's needed to be converted to buffer, it 's quite hard :))
