### ISSUE TITLE
zklibtcp getAttendaces error on line 306

### ISSUE THREAD

**Issue by csulit** [caobo171/node-zklib#21]
zklibtcp.js:306
                cb(replyData.length, size);
                ^
TypeError: cb is not a function
    at Socket.handleOnData (C:\Users\KMCS\Documents\node-zklib-v2\zklibtcp.js:306:17)

```
    const attendances = await zkInstance.getAttendances('10.20.0.7', (percent, total)=>{
        // this callbacks take params is the percent of data downloaded and total data need to download 
    })
```

**Comment by caobo171** [comment]
I think some thing was wrong in my code !!

**Comment by caobo171** [comment]
I removed the first params in this function , sorry for updating :D
