### ISSUE TITLE
Using TCP on port 80

### ISSUE THREAD

**Issue by riadh2002** [caobo171/node-zklib#25]
If I try to set the port to TCP80 instead of UDP4370 
  let zkInstance = new ZKLib(192.168.1.202, 80, 10000, 4000);

I get the follwing error:

ZKError {
  err: Error: TIMEOUT_ON_WRITING_MESSAGE
      at Timeout.<anonymous> (nodejs\node_modules\node-zklib\zklibtcp.js:100:22)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7),
  ip: '192.168.1.202',
  command: 'TCP CONNECT'
}

is there any other considerations to take into account to use TCP instead of UDP?

the reason of using TCP is to get more user info (password, cardID) which are not available through UDP

thanks

**Comment by caobo171** [comment]
Oh, it depends on your device, some device use UDP, some use TCP, I covered it in my code, but I didn't see a device use port 80 before, it usually uses port 4370 both for TCP or UDP

**Comment by riadh2002** [comment]
Thanks,

it seems the TCP error is also thrown if a pointing device is outside the local network example: ip=device.ddns.net that resolves to 80.90.100.110, even-though both 80 and 4370 ports are open and the device is accessible using ZK software on 4370 and through the browser on port 80.

`ZKError {
  err: Error: connect ETIMEDOUT 80.90.100.110:4370
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '80.90.100.110',
    port: 4370
  },
  ip: 'device.ddns.net',
  command: 'TCP CONNECT'
}
(node:9112) UnhandledPromiseRejectionWarning: #<ZKError>
(node:9112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:9112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I wonder if this is a known limitation?

**Comment by riadh2002** [comment]
Hello again,

OK using your comment about port 4370 as UDP and TCP, I opened port 4370 on TCP and tried and it worked!!!

So for this to work, port 4370 must be open on TCP and not UDP.

thank you

**Comment by caobo171** [comment]
> Thanks,
> 
> it seems the TCP error is also thrown if a pointing device is outside the local network example: ip=device.ddns.net that resolves to 80.90.100.110, even-though both TCP80 and UDP4370 ports are open and the device is accessible using ZK software
> 
> ZKError {
> err: Error: connect ETIMEDOUT 80.90.100.110:4370
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '80.90.100.110',
> port: 4370
> },
> ip: 'device.ddns.net',
> command: 'TCP CONNECT'
> }
> 
> I wonder if there is a port problem here?

I think it's my lib's problem, but I can't fix this now with my resource, all my test devices are used in my company so it's hard for me to request them open another port

**Comment by caobo171** [comment]
> Hello again,
> 
> OK using your comment about port 4370 as UDP and TCP, I opened port 4370 on TCP and tried and it worked!!!
> 
> So for this to work, port 4370 must be open on both TCP and UDP and the program chooses which one to use.
> 
> But one issue is when the program chooses TCP, the getUsers will not return the password and Card Number?
> 
> thank you

glad to hear that, the missing properties is caused by lacking document, I don't know how to extract it :(
