### ISSUE TITLE
How to get the latest check-in attendance data

### ISSUE THREAD

**Issue by ntahlahweh** [caobo171/node-zklib#3]
Hello, I would like to ask how to get the latest check-in attendance data?

**Comment by csulit** [comment]
@ntahlahweh filter it with the latest date.

**Comment by ntahlahweh** [comment]
I see, but my idea is to get the last name in the array instead. Is it possible to do that?

I'm sorry as I'm not really experience in Javascript

**Comment by caobo171** [comment]
We need to load all data , then sort it by date , there is no way  to paginate the data , unfortunatelyy
