### ISSUE TITLE
How to configure node-zklib for multiple terminal

### ISSUE THREAD

**Issue by azad71** [caobo171/node-zklib#34]
I need to get realtime log from multiple terminal. Current library is configured for single ip. Is there any way to add multiple ip and listen to them for realtime log?

**Comment by imfaisii** [comment]
https://github.com/rabbygit/node_zklib
this repo extends it and added multiple device realtime logs , btw can you let me know how are you getting realtime logs ? I am new to nodejs , i am running on terminal node test.js and uncommented the realtimelogs function , but it is returning me nothing

**Comment by azad71** [comment]
The repo you mentioned, I believe you already found a solution there. We actually work together :D
